---
title: "seqtools help documentation"
author: 向旸
output: html_notebook
---
# **SEQTOOLS**
 *Used to facilitate some text message processing work, if you encountered errors please communicate with me!*\
## introduction
The tool is designed to be used for a variety of purposes related to sequence processing and supports the reading of logs produced by hisat2 and blast.Subsequent updates are expected on the extraction of the longest transcripts.\
## EXTRACT GENES RANDOM
This option allow randomized extraction sequence ,default seed is 10,you also can key input your seed you need. \
## SORT FASTA BY LENGTH
Sort the sequences by length, default is from shortest to longest, you can use reverse '-r'\
## SHUFFLE
Perform a randomized disruption of the sequence.\
## SUB SEQ
Extract the gene as provided in sample.txt\
## BY ID
use nucle acid as reference\
## SEQUENCE STATISTICS
Read the sequences and count the N50, total length, and GC content of the sequences to evaluate the assembly results.\
And if you use trinity ouput fasta file, you can key in '-t' to get the gene statistics of the transcripts.\
